### ISSUE TITLE
QT version requirement.

### ISSUE THREAD

**Issue by Achaean** [jasonsikes/QLogo#24]
At front page, is mentioned that Qt v.5.6.3 is required, but trying to run QLogo, returns:
```
>./QLogo-Linux-x86_64
./QLogo-Linux-x86_64: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by ./QLogo-Linux-x86_64)
>
```

I have QT v.5.7.1, which meets front page's requirement, but it seems like the actual requirement is QT v.5.10.

**Comment by jasonsikes** [comment]
That is an error on my part. Qt_5.10 is what I am using on my system to build the binaries that I published on the web page. So if I build on my system and publish the binaries then the binaries expect the same libraries on your system than I have on mine.

The solution to this is to just not publish the binaries on Linux, and instead write better instructions for building it yourself.

**Comment by Achaean** [comment]
**THANKS** Jason!!! :-)
I'll wait for the instructions!

**Comment by jasonsikes** [comment]
Hi, Achaean.

I usually use qtcreator to build QLogo, but I just figured out on the command line you should be able to build it like this:

$ qmake-qt5 QLogo.pro
$ make

And, optionally:
$ sudo make install

It's a lot easier than I thought it would be.

--Thank you,
--Jason

**Comment by Achaean** [comment]
> Hi, Achaean.
> 
Hi! :-)
> 
> $ qmake-qt5 QLogo.pro

I think is "qmake QLogo.pro" on Debian based systems. (I'm on Devuan ASCII (stable) x64 KDE, Debian stable based).
Completed successfully.
> $ make
> 
Also completed successfully.

> And, optionally:
> $ sudo make install
> 
"make install" (as root), failed! (make: Nothing to be done for 'install').
However, it runs perfectly from it's directory. :-)

**Comment by jasonsikes** [comment]
Thank you so much. I don't know why I assumed that 'make install' would work. I didn't try it out because I am on my work computer and don't want to sudo anything that isn't work-related.

Also, on my system the first command is 'qmake-qt5'. 'qmake' builds for QT4 projects. That's something else I'm going to include in my instructions. Thank you for that bit on insight.

**Comment by Achaean** [comment]
;-)
