### ISSUE TITLE
SETHEADING is mirrored

### ISSUE THREAD

**Issue by pdewacht** [jasonsikes/QLogo#42]
I think `SETHEADING 90` is supposed to point the turtle to the right. Instead it points the turtle to the left.

I was trying some examples from old books with Debian's qlogo 0.92.

**Comment by jasonsikes** [comment]
You are correct. I chose heading to go counter-clockwise since that is the traditional computer graphics direction, but as I am aiming for Logo compatibility, I'll go the other way instead. Thank you.
