### ISSUE TITLE
installs executables in /usr/ instead of /usr/bin/

### ISSUE THREAD

**Issue by barak** [jasonsikes/QLogo#45]
The line
```
install(TARGETS QLogo logo RUNTIME DESTINATION . BUNDLE DESTINATION ${CMAKE_INSTALL_BINDIR})
```
in `CMakeLists.txt` installs the executables in `/usr/` instead of `/usr/bin/` using the default Debian build scripts.

**Comment by jasonsikes** [comment]
There are a bunch of things I will have to learn about CMake.

In the meantime, would this work instead?

`${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}`

**Comment by barak** [comment]
I dunno; I treasure my ignorance of cmake!

**Comment by jasonsikes** [comment]
Yeah, I don't want to learn it either, but I will have to. I still need to figure out how to install libraries and help files.

**Comment by jasonsikes** [comment]
CMake has been updated. Now installs files where they should go. Thanks!
