### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jasonsikes** [jasonsikes/QLogo#6]
The code needs documentation. Lots of it.

**Comment by Achaean** [comment]
Hi! :-)

1) Also Berkeley Logo, seems to be incompatible with QLogo.
The manual at front page, needs to be replaced.

2) I think compilation instructions are of top priority and there's a need to be written even before the entire documentation.

**Comment by Achaean** [comment]
Just a question! :-)

Are the LOGO commands hardcoded?
Ca someone find them, somewhere at source files?

**Comment by jasonsikes** [comment]
Yes. They are hardcoded. You can find the LOGO commands in the source code by looking at 'parser.cpp'. It's a big file so search for 'stringToCmd'. You'll see a lot of lines that look like this:


  stringToCmd["WORD"] = {&Kernel::excWord, 0, 2, -1};
  stringToCmd["LIST"] = {&Kernel::excList, 0, 2, -1};
  stringToCmd["SENTENCE"] = {&Kernel::excSentence, 0, 2, -1};
  stringToCmd["SE"] = stringToCmd["SENTENCE"];

As you can guess, the commands here are 'WORD', 'LIST', and 'SENTENCE'. ('SE' is an abbreviation for 'SENTENCE'.)

The toolkit that I am using has a neat mechanism for facilitating translations to other languages (French, Spanish, etc.), but I don't have QLogo set up correctly to allow translations yet.

**Comment by Achaean** [comment]
Great! :-)
I'll check it.

**Comment by jasonsikes** [comment]
README.md has been updated with build instructions. LOGO command help files are integrated with the sources so we can see what the command is supposed to do. Header file documentation is still ongoing and will be perpetual, so I am going to close this ticket to clear my ticket "clutter".
